/** Principal identity — resolve a raw principal, hash it at the edge.
 *
 * The TypeScript half of Python's `baton/identity.py`. Baton attaches the
 * resolved principal to every event so the Console can group by
 * `(tenant_id, vendor_id, principal.id)`, at whatever grain the vendor
 * resolved (SPEC §11.4).
 *
 * Residency contract: the Console DB is metadata-only and may only ever see
 * the HASH — raw identity must never leave the capture edge. So hashing
 * happens HERE, before an event reaches any console-bound sink.
 *
 * ⚠ **This file and Python's must produce byte-identical digests**, and that
 * is asserted rather than believed: `test/identity.test.ts` runs a corpus
 * GENERATED from Python (`test/identityVectors.json`, regenerated by
 * `scripts/gen_identity_vectors.py`) and compares strings. Same discipline as
 * `scrub.ts` — though NOT its method, which was a hand-mirrored matrix, not a
 * generated corpus — for the same reason: one person reaching two SDKs must be one
 * actor downstream, and nothing but a differential corpus can prove it.
 */

import { createHmac } from "node:crypto";

import { capCodePoints, exceedsCodePoints } from "./_text.js";

// ⚠ **`HASH_SCHEME = "h1"` lived here and is GONE at 0.4.1** (SPEC §11.4, §13
// entry 0.8.11), together with `hashPrincipalId`'s `scheme` option. A hashed
// principal is the BARE digest: no tag, no prefix, no scheme.
//
// It named the HMAC key generation, and a fact ABOUT a value must not ride
// INSIDE the value — the rule `PrincipalWire`'s three members exist to make
// structural. Provenance is `source`, the classification is `form`, and both
// ride every mode including `"raw"`, where no tag ever existed.
//
// ⚠ **What went with it:** nothing now records WHICH key produced a digest, so
// rotating the secret replaces a tenant's whole population with no marker
// anywhere. Accepted — the generation could not have re-joined a person across
// the boundary anyway. It was also an EXPORT, so a vendor recomputing a
// pseudonym against its own copy gets a tagged value from the old one and a
// bare value from this one.

/** Where a principal came from. `"asserted"` is a vendor's own resolver,
 * which nothing in the protocol checks, and is the only value this SDK
 * emits — `integrations/mcp/principalResolution.ts` has the why, and the
 * wording trap that comes with it. */
export const PRINCIPAL_SOURCE_ASSERTED = "asserted";

/** What the emitted value IS — the privacy classification, and the only thing
 * SPEC §11.4 lets a consumer classify on. */
export const PRINCIPAL_FORM_HASHED = "hashed";
export const PRINCIPAL_FORM_RAW = "raw";

/** Ceiling on a RAW principal id, mirroring Python's `RAW_PRINCIPAL_ID_MAX_LEN`.
 *
 * Raw mode copies vendor-supplied text onto EVERY event of a call — three
 * tool-call legs plus any annotation — so an unbounded value is unbounded
 * several times over. A hook returning a JWT or a concatenated gateway header
 * is the realistic shape, not a hostile one. */
export const RAW_PRINCIPAL_ID_MAX_LEN = 128;

/** Cap on `displayName`, in CODE POINTS (Python's `len`). Over it the name is
 * DROPPED, not truncated: SPEC §11.4 forbids rewriting it, so both SDKs send
 * the same bytes for one resolver output. */
export const DISPLAY_NAME_MAX_LEN = 128;

// Unicode `White_Space`, exactly (SPEC §11.4's blank rule). Not `.trim()`:
// that also removes U+FEFF and keeps U+0085, which Python's `strip()` does the
// other way round, so the two SDKs would disagree on what is blank.
const ALL_WHITE_SPACE = /^\p{White_Space}*$/u;

/** The resolver's `displayName` as it goes on the wire, or `null`. Verbatim
 * when usable. A non-string, a blank (only Unicode `White_Space`), an
 * over-long value or one holding a lone surrogate is dropped ALONE — the rest
 * of the principal still ships, because a bad label is no reason to lose a
 * good id. Mirrors Python's `wire_display_name`. */
export function wireDisplayName(value: unknown): string | null {
  if (typeof value !== "string" || exceedsCodePoints(value, DISPLAY_NAME_MAX_LEN)) return null;
  if (LONE_SURROGATE.test(value) || ALL_WHITE_SPACE.test(value)) return null;
  return value;
}

export const PRINCIPAL_ID_MODE_HASHED = "hashed";
export const PRINCIPAL_ID_MODE_RAW = "raw";
export type PrincipalIdMode = typeof PRINCIPAL_ID_MODE_HASHED | typeof PRINCIPAL_ID_MODE_RAW;

export type PrincipalForm = typeof PRINCIPAL_FORM_HASHED | typeof PRINCIPAL_FORM_RAW;

/** `principalIdMode` names a CONFIG choice; `form` names what the emitted
 * value IS. The two vocabularies coincide today and are still two
 * vocabularies — a mode added later need not name its form the same thing,
 * and a consumer classifies on `form` alone.
 *
 * Written out rather than derived, so a third mode cannot silently become a
 * third `form`: the `Record` makes it a COMPILE ERROR until someone chooses
 * what the new mode means for a consumer's classification. That
 * exhaustiveness is the payoff — `form: options.mode` would put an unexamined
 * new mode name straight onto the wire. */
const FORM_BY_MODE: Record<PrincipalIdMode, PrincipalForm> = {
  [PRINCIPAL_ID_MODE_HASHED]: PRINCIPAL_FORM_HASHED,
  [PRINCIPAL_ID_MODE_RAW]: PRINCIPAL_FORM_RAW,
};

/** The registered modes, DERIVED from the map above exactly as Python derives
 * `PRINCIPAL_ID_MODES = frozenset(_FORM_BY_MODE)`.
 *
 * ⚠ **This closes the other direction, and `principalFor` depends on it.**
 * That function drops Python's unrecognised-mode branch on the grounds that
 * config validation refuses an unknown mode first. With a second hand-written
 * list the guarantee would be only "two lists happen to agree" — the
 * prose-shaped binding this whole change exists to replace. Derived, a mode
 * cannot be accepted by the validator without someone having chosen its
 * `form`. */
export const PRINCIPAL_ID_MODES: readonly PrincipalIdMode[] = Object.keys(
  FORM_BY_MODE,
) as PrincipalIdMode[];

/** Codepoints Python's `str.strip()` removes, measured against CPython rather
 * than assumed — `\s` in JavaScript is the WRONG set in BOTH directions.
 *
 * JS `\s` omits `\x1c`-`\x1f` and `\x85`, which Python strips; and JS `\s`
 * INCLUDES `U+FEFF`, which Python does not. So a BOM-prefixed subject is
 * trimmed by one language and kept by the other, and that subject
 * subject — the shape a value pasted out of a spreadsheet or read from a
 * BOM'd file arrives in — would hash to two different actors across the two
 * SDKs. `.trim()` is therefore never correct here; the corpus carries that
 * exact vector. */
const PYTHON_WHITESPACE = "\\t\\n\\v\\f\\r\\x1c-\\x1f \\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000";
const PYTHON_STRIP = new RegExp(`^[${PYTHON_WHITESPACE}]+|[${PYTHON_WHITESPACE}]+$`, "gu");

/** Matches a string containing an UNPAIRED surrogate.
 *
 * `String.prototype.isWellFormed()` says the same thing more plainly, but it
 * needs `lib: ES2024` and this package declares `ES2022` — a lib bump is a
 * statement about what every consumer must support, which is too broad a
 * change to make for one predicate. Under the `u` flag a valid pair is a
 * single code point and does NOT match, while a lone half does; verified to
 * agree with `isWellFormed()` on both. */
const LONE_SURROGATE = /\p{Surrogate}/u;

/** Pin the principal string once, centrally, so every modality hashes an
 * identical value: NFC-normalize, strip, lowercase — in that order, which is
 * Python's order and is load-bearing (normalizing after stripping can expose
 * new strippable codepoints). */
function canonicalize(rawPrincipal: string): string {
  return pythonStrip(rawPrincipal.normalize("NFC")).toLowerCase();
}

/** Python's `str.strip()`, over exactly the set above. Exported for the
 * server-name rule in `integrations/mcp/annotationName.ts`, which has to agree
 * with Python's on what counts as a blank name. */
export function pythonStrip(value: string): string {
  return value.replace(PYTHON_STRIP, "");
}

/** A raw, UNHASHED principal, as a resolver produced it. */
export interface Principal {
  /** The subject — a stable identifier from the vendor's own
   * system. Never an application id: that names the app and is identical for
   * every one of its users, which merges them into one actor. */
  principalId: string;
  /** The issuing authority, where one exists (the OIDC `iss`). Folded into
   * the hash because a subject is unique only within the provider that minted
   * it, so two identity providers behind one vendor can hand the same subject
   * to different people. */
  issuer?: string | null | undefined;
  /** What a page shows for this principal — `principalFromOAuthEmail` puts
   * the part of the address before the last `@` here. **Sent verbatim, in
   * every mode, hashed included, and never through the scrubber** (SPEC
   * §11.4): the vendor chooses what is safe to show. An unusable value is
   * dropped alone — see `wireDisplayName`. */
  displayName?: string | null | undefined;
}

/** HMAC-SHA256 a raw principal into a console-safe, per-tenant `principal.id`.
 *
 * `tenantId` is folded into the HMAC MESSAGE (not just the key) so the same
 * principal under two tenants can never collide or be cross-tenant-correlated.
 * Returns the BARE lowercase hex digest — no tag, no prefix, no scheme. It
 * returned `"h1:<hex>"` until 0.4.1; the tag was never part of the HMAC
 * message, so taking it off moved no digit of the digest.
 *
 * ⚠ **`issuer` null/undefined MUST hash byte-identically to the pre-issuer
 * form** — the append-only message layout is what guarantees it, and every
 * hash baton-proxy and baton-extmcp have produced since 0.5.0 was issuer-less.
 */
export function hashPrincipalId(
  rawPrincipal: string,
  options: {
    tenantId: string;
    key: Uint8Array | string;
    // `| undefined` explicitly, because this repo runs
    // `exactOptionalPropertyTypes`: an optional property there does NOT admit
    // an explicitly-passed `undefined`, and callers forward an absent issuer
    // as one. Both spellings must mean "no issuer" or the two arms of that
    // caller hash differently.
    issuer?: string | null | undefined;
    // ⚠ `scheme?: string` was here until 0.4.1 and is REMOVED, not deprecated.
    // A keyword left in place is an invitation to pass one, and there is no
    // longer any tag for it to select.
  },
): string {
  const { tenantId, key, issuer = null } = options;
  let message = `${tenantId}\x00${canonicalize(rawPrincipal)}`;
  // `!== null` alone: the destructure above defaults an explicitly-passed
  // `undefined` to `null`, so only one of the two states survives it. The
  // `| undefined` in the option TYPE stays — that is what
  // `exactOptionalPropertyTypes` needs at the call boundary.
  if (issuer !== null) {
    message += `\x00${canonicalize(issuer)}`;
  }
  // A string key is UTF-8 encoded, matching Python's env-var path
  // (`BATON_PRINCIPAL_ID_HMAC_KEY` arrives as text and is `.encode()`d there).
  const keyBytes = typeof key === "string" ? Buffer.from(key, "utf8") : key;
  return createHmac("sha256", keyBytes).update(message, "utf8").digest("hex");
}

/** Normalize whatever a vendor's hook returned into a usable `Principal`, or
 * `null` if it gave us nothing usable.
 *
 * ⚠ **The shape check is load-bearing, not defensive typing.** TypeScript
 * types vanish at runtime and a hook is vendor code, so a plain string, a
 * dict, or a half-built object is exactly what arrives first — AgentCat's
 * `identify()`, the prior art this is modelled on, returns a bare object. The
 * very next thing that happens to this value is an HMAC over `principalId`, so a
 * wrong return is a MISS, never a partially-built principal.
 *
 * ⚠ **An empty or whitespace-only `principalId` is REJECTED**, and this is a
 * measured divergence from the prior art rather than a stylistic one: their
 * guard is falsy-only, so `{principalId: ""}` reaches their wire. An empty
 * principal canonicalizes to `""` and hashes to one stable digest naming
 * nobody — so every such caller merges into a single phantom actor, which is
 * the exact failure this field exists to prevent.
 */
export function normalizePrincipal(result: unknown): Principal | null {
  if (result === null || typeof result !== "object") return null;
  const candidate = result as { principalId?: unknown; issuer?: unknown; displayName?: unknown };
  if (typeof candidate.principalId !== "string") return null;
  // ⚠ **A lone surrogate MERGES distinct people, so it is a miss.** Node's
  // `update(…, "utf8")` does not throw on an unpaired surrogate — it replaces
  // it with U+FFFD — so `"a\uD800"`, `"a\uDC00"` and `"a\uFFFD"` all hash to
  // ONE digest (measured). That is the actor merge this module exists to
  // prevent, arriving through the quietest possible door. Python raises
  // `UnicodeEncodeError` on `.encode()` and drops the field, so refusing here
  // is also what keeps the two arms agreeing: same input, same answer (none).
  // Reachable from a subject sliced out of a JSON payload or a header.
  if (LONE_SURROGATE.test(candidate.principalId)) return null;
  // `.strip()`-equivalent, because the canonicalizer strips: a whitespace-only
  // subject is a phantom actor every such caller merges into.
  if (canonicalize(candidate.principalId) === "") return null;

  // ⚠ **This guard is falsy-not-stripped, and that is a KNOWN PAIRED DEFECT
  // carried deliberately rather than fixed here.** Python's
  // `identity_adapter.py` uses the same truthiness test, so a whitespace-only
  // issuer passes BOTH and then canonicalizes to `""` — producing a digest
  // distinct from both a null issuer and an empty one, i.e. one person as two
  // actors. Fixing it on this arm alone would split every issuer-bearing hash
  // across the two SDKs, which is a worse bug than the one being fixed. The
  // corpus pins the shared behaviour (`issuer WHITESPACE-ONLY`), so whichever
  // arm is corrected first reddens the other and forces the paired change.
  const issuerRaw = typeof candidate.issuer === "string" && candidate.issuer ? candidate.issuer : null;
  // A malformed ISSUER costs the issuer, not the identity — the subject still
  // resolves, which is the difference between a degraded actor and no actor.
  //
  // ⚠ **This DIVERGES from Python and the corpus structurally cannot pin it.**
  // There, `hash_principal_id` raises `UnicodeEncodeError` on the issuer and
  // `_finish_principal` drops the principal entirely; here the subject still
  // hashes, issuer-less — so the same input yields no field on one arm and a
  // digest on the other, one that collides with the same `sub` from a
  // different IdP. Recorded rather than aligned, because dropping a resolvable
  // identity over a malformed issuer is the worse behaviour. The generated
  // corpus cannot carry this case: Python's generator cannot produce a vector
  // for an input that raises.
  const issuer = issuerRaw !== null && !LONE_SURROGATE.test(issuerRaw) ? issuerRaw : null;
  // Shape only; the name's own rules run once, in `principalFor`.
  return typeof candidate.displayName === "string"
    ? { principalId: candidate.principalId, issuer, displayName: candidate.displayName }
    : { principalId: candidate.principalId, issuer };
}

/** The principal AS EMITTED — the finished envelope value (SPEC §11.4).
 *
 * ⚠ **Not `Principal`, and the two are easy to confuse.** That one is what a
 * vendor's `resolvePrincipal` hook HANDS US: a raw subject and an optional
 * issuer. This one is what we PUT ON THE WIRE after deriving it — the raw
 * value is gone by the time this is built, and nothing here is ever the input
 * to a hash. One is the question, this is the answer.
 *
 * **All three members are REQUIRED, and that is the guarantee the object
 * exists to give.** A producer emits the whole thing or omits `principal`
 * entirely; a partial object is malformed, not a degraded reading. So there is
 * no conformant event carrying an `id` whose `form` a consumer has to guess,
 * and none carrying a `source` for an identity nobody resolved. That binding
 * is structural here precisely because its predecessor — a scheme prefix plus
 * a paragraph of prose — was not.
 */
export interface PrincipalWire {
  /** The value: an HMAC pseudonym in `"hashed"` mode, the principal verbatim
   * in `"raw"` mode. Which one is `form`, and it is NEVER the value's shape —
   * a real OIDC subject (`mailto:`, `acct:`, `urn:`, `https:`) reads as a
   * scheme-tagged pseudonym to anything testing for "letters then a colon". */
  id: string;
  /** WHERE it came from. Always `"asserted"` here — `principalResolution.ts`
   * has the why and the wording trap. */
  source: typeof PRINCIPAL_SOURCE_ASSERTED;
  /** WHAT it is. */
  form: PrincipalForm;
  /** What a page shows; personal data whenever present, whatever `form`
   * says. OMITTED, never `null`, when there is none — so a nameless principal
   * is byte-identical to one from before the member existed. */
  display_name?: string;
}

// ⚠ **Literal types here, `z.string()` on `PrincipalWireSchema` — and the
// asymmetry is deliberate.** That schema is the PARSE boundary and must
// tolerate a value SPEC registers later; this is the PRODUCER type, and this
// SDK emits exactly one `source` and two `form`s. Widening it would inherit
// the schema's justification without its reason, and would let a stray
// string through. Typed this way, adding a source is a compile error in one
// place — here, where the registry is.

/** Turn a resolved principal into the finished wire object, or `null`.
 *
 * **The edge-derivation chokepoint, and the single copy of it**, mirroring
 * Python's `_finish_principal`. `raw` mode puts real identity in the
 * collector's database — the vendor's deliberate choice, and why SPEC §11.4
 * tells a consumer never to treat a principal as anonymous unless `form` says
 * exactly `"hashed"`.
 *
 * ⚠ **Hashed mode with no key DROPS the principal rather than falling back to
 * raw.** The fallback would be a residency breach that looks like success: the
 * field present, populated, and carrying the subject verbatim. Absent is the
 * safe direction — this is additive analytics and never a consent gate.
 *
 * **All three members or nothing**, and structurally so: there is exactly ONE
 * object literal in this function, at the bottom, and every branch that cannot
 * produce a value returns `null` before reaching it.
 *
 * ⚠ Python carries a fourth failure branch here — an unrecognised `mode`,
 * which has no truthful `form`. It is unreachable on this arm:
 * `validateConfig` (`integrations/mcp/config.ts`) refuses an unknown
 * `principalIdMode` at install, so the mode reaching this function is always
 * one of the two. Not porting it is therefore a fact about where the check
 * lives, not a gap.
 */
export function principalFor(
  principal: Principal,
  options: {
    mode: PrincipalIdMode;
    tenantId: string;
    key?: Uint8Array | string | null | undefined;
  },
): PrincipalWire | null {
  let id: string;
  if (options.mode === PRINCIPAL_ID_MODE_RAW) {
    // `capCodePoints`, not `.slice()`: a plain slice counts UTF-16 units, so
    // an astral subject cut at the boundary ships a LONE SURROGATE — the very
    // thing `normalizePrincipal` refuses on the way IN — and disagrees with
    // Python's `principal_id[:128]`, which counts code points.
    //
    // ⚠ What raw mode NO LONGER forfeits is the provenance: `source` is a
    // member now and rides every mode, so a consumer here is told a real
    // identity AND which mechanism named it.
    id = capCodePoints(principal.principalId, RAW_PRINCIPAL_ID_MAX_LEN);
  } else {
    if (options.key === null || options.key === undefined) return null;
    id = hashPrincipalId(principal.principalId, {
      tenantId: options.tenantId,
      key: options.key,
      issuer: principal.issuer ?? null,
    });
  }
  // Unconditional `source`: every principal comes from the vendor's hook
  // (SPEC §11.4), so an option here would be an argument no caller can vary.
  const wire: PrincipalWire = {
    id,
    source: PRINCIPAL_SOURCE_ASSERTED,
    form: FORM_BY_MODE[options.mode],
  };
  // Checked HERE, where every wire object is built (Python: `_finish_principal`).
  const displayName = wireDisplayName(principal.displayName);
  if (displayName !== null) wire.display_name = displayName;
  return wire;
}
