/** End-user identity — resolve a raw principal, hash it at the edge.
 *
 * The TypeScript half of Python's `baton/identity.py`. Baton attaches an
 * end-user actor (`user_id`) to every event so the Console can answer "which
 * *customer* hit this" and group by `(tenant_id, vendor_id, user_id)`.
 *
 * Residency contract: the Console DB is metadata-only and may only ever see
 * the HASH — raw identity must never leave the capture edge. So hashing
 * happens HERE, before an event reaches any console-bound sink.
 *
 * ⚠ **This file and Python's must produce byte-identical digests**, and that
 * is asserted rather than believed: `test/identity.test.ts` runs a corpus
 * GENERATED from Python (`test/identityVectors.json`, regenerated by
 * `scripts/gen_identity_vectors.py`) and compares strings. Same discipline as
 * `scrub.ts` — though NOT its method, which was a hand-mirrored matrix, not a
 * generated corpus — for the same reason: one person reaching two SDKs must be one
 * actor downstream, and nothing but a differential corpus can prove it.
 */

import { createHmac } from "node:crypto";

import { capCodePoints } from "./_text.js";

/** The ATTESTED derivation tag — a principal read off a verified token. */
export const HASH_SCHEME = "h1";

/** The ASSERTED derivation tag — a principal a vendor's own hook supplied.
 *
 * Deliberately outside the `h*` family: `h2:` is reserved for HMAC key
 * rotation, so a vendor assertion must never be mistakable for an
 * attestation (SPEC §11.4's registered-set rule). */
export const VENDOR_HASH_SCHEME = "v1";

/** Ceiling on a RAW `user_id`, mirroring Python's `RAW_USER_ID_MAX_LEN`.
 *
 * Raw mode copies vendor-supplied text onto EVERY event of a call — three
 * tool-call legs plus any annotation — so an unbounded value is unbounded
 * several times over. A hook returning a JWT or a concatenated gateway header
 * is the realistic shape, not a hostile one. */
export const RAW_USER_ID_MAX_LEN = 128;

export const USER_ID_MODE_HASHED = "hashed";
export const USER_ID_MODE_RAW = "raw";
export type UserIdMode = typeof USER_ID_MODE_HASHED | typeof USER_ID_MODE_RAW;

/** Codepoints Python's `str.strip()` removes, measured against CPython rather
 * than assumed — `\s` in JavaScript is the WRONG set in BOTH directions.
 *
 * JS `\s` omits `\x1c`-`\x1f` and `\x85`, which Python strips; and JS `\s`
 * INCLUDES `U+FEFF`, which Python does not. So a BOM-prefixed subject is
 * trimmed by one language and kept by the other, and that subject
 * subject — the shape a value pasted out of a spreadsheet or read from a
 * BOM'd file arrives in — would hash to two different actors across the two
 * SDKs. `.trim()` is therefore never correct here; the corpus carries that
 * exact vector. */
const PYTHON_WHITESPACE = "\\t\\n\\v\\f\\r\\x1c-\\x1f \\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000";
const PYTHON_STRIP = new RegExp(`^[${PYTHON_WHITESPACE}]+|[${PYTHON_WHITESPACE}]+$`, "gu");

/** Matches a string containing an UNPAIRED surrogate.
 *
 * `String.prototype.isWellFormed()` says the same thing more plainly, but it
 * needs `lib: ES2024` and this package declares `ES2022` — a lib bump is a
 * statement about what every consumer must support, which is too broad a
 * change to make for one predicate. Under the `u` flag a valid pair is a
 * single code point and does NOT match, while a lone half does; verified to
 * agree with `isWellFormed()` on both. */
const LONE_SURROGATE = /\p{Surrogate}/u;

/** Pin the principal string once, centrally, so every modality hashes an
 * identical value: NFC-normalize, strip, lowercase — in that order, which is
 * Python's order and is load-bearing (normalizing after stripping can expose
 * new strippable codepoints). */
function canonicalize(rawPrincipal: string): string {
  return rawPrincipal.normalize("NFC").replace(PYTHON_STRIP, "").toLowerCase();
}

/** A raw, UNHASHED end-user principal, as a resolver produced it. */
export interface Principal {
  /** The subject — a stable per-person identifier from the vendor's own
   * system. Never an application id: that names the app and is identical for
   * every one of its users, which merges them into one actor. */
  userId: string;
  /** The issuing authority, where one exists (the OIDC `iss`). Folded into
   * the hash because a subject is unique only within the provider that minted
   * it, so two identity providers behind one vendor can hand the same subject
   * to different people. */
  issuer?: string | null | undefined;
}

/** HMAC-SHA256 a raw principal into a console-safe, per-tenant `user_id`.
 *
 * `tenantId` is folded into the HMAC MESSAGE (not just the key) so the same
 * principal under two tenants can never collide or be cross-tenant-correlated.
 * Returns `"<scheme>:<hex>"`.
 *
 * `scheme` tags the DERIVATION and only the tag changes — the digest for a
 * given `(tenantId, principal, issuer)` is identical under every scheme,
 * because the tag is not part of the message. That is deliberate: the same
 * person reached by two provenances is meant to be recognisably the same hex
 * under two tags, not two unrelated values.
 *
 * ⚠ **`issuer` null/undefined MUST hash byte-identically to the pre-issuer
 * form** — the append-only message layout is what guarantees it, and every
 * hash baton-proxy and baton-extmcp have produced since 0.5.0 was issuer-less.
 */
export function hashUserId(
  rawPrincipal: string,
  options: {
    tenantId: string;
    key: Uint8Array | string;
    // `| undefined` explicitly, because this repo runs
    // `exactOptionalPropertyTypes`: an optional property there does NOT admit
    // an explicitly-passed `undefined`, and callers forward an absent issuer
    // as one. Both spellings must mean "no issuer" or the two arms of that
    // caller hash differently.
    issuer?: string | null | undefined;
    /** ⚠ **REQUIRED, and deliberately NOT defaulted the way Python's is.**
     * Python defaults to `HASH_SCHEME` (`h1:`), which is right there because
     * that arm emits both provenances. This arm emits ONLY `v1:` — it has no
     * attested rung — so an `h1:` default would hand the documented
     * "recompute the pseudonym to join your own records against Console data"
     * use a value matching nothing we ever wrote, forever, with an equality
     * join silently returning zero rows. The hex halves are identical under
     * both tags, so it fails in the most confusing way available. Naming the
     * provenance is one word and removes the whole failure. */
    scheme: string;
  },
): string {
  const { tenantId, key, issuer = null, scheme } = options;
  let message = `${tenantId}\x00${canonicalize(rawPrincipal)}`;
  // `!== null` alone: the destructure above defaults an explicitly-passed
  // `undefined` to `null`, so only one of the two states survives it. The
  // `| undefined` in the option TYPE stays — that is what
  // `exactOptionalPropertyTypes` needs at the call boundary.
  if (issuer !== null) {
    message += `\x00${canonicalize(issuer)}`;
  }
  // A string key is UTF-8 encoded, matching Python's env-var path
  // (`BATON_USER_ID_HMAC_KEY` arrives as text and is `.encode()`d there).
  const keyBytes = typeof key === "string" ? Buffer.from(key, "utf8") : key;
  const digest = createHmac("sha256", keyBytes).update(message, "utf8").digest("hex");
  return `${scheme}:${digest}`;
}

/** Normalize whatever a vendor's hook returned into a usable `Principal`, or
 * `null` if it gave us nothing usable.
 *
 * ⚠ **The shape check is load-bearing, not defensive typing.** TypeScript
 * types vanish at runtime and a hook is vendor code, so a plain string, a
 * dict, or a half-built object is exactly what arrives first — AgentCat's
 * `identify()`, the prior art this is modelled on, returns a bare object. The
 * very next thing that happens to this value is an HMAC over `userId`, so a
 * wrong return is a MISS, never a partially-built principal.
 *
 * ⚠ **An empty or whitespace-only `userId` is REJECTED**, and this is a
 * measured divergence from the prior art rather than a stylistic one: their
 * guard is falsy-only, so `{userId: ""}` reaches their wire. An empty
 * principal canonicalizes to `""` and hashes to one stable digest naming
 * nobody — so every such caller merges into a single phantom actor, which is
 * the exact failure this field exists to prevent.
 */
export function normalizePrincipal(result: unknown): Principal | null {
  if (result === null || typeof result !== "object") return null;
  const candidate = result as { userId?: unknown; issuer?: unknown };
  if (typeof candidate.userId !== "string") return null;
  // ⚠ **A lone surrogate MERGES distinct people, so it is a miss.** Node's
  // `update(…, "utf8")` does not throw on an unpaired surrogate — it replaces
  // it with U+FFFD — so `"a\uD800"`, `"a\uDC00"` and `"a\uFFFD"` all hash to
  // ONE digest (measured). That is the actor merge this module exists to
  // prevent, arriving through the quietest possible door. Python raises
  // `UnicodeEncodeError` on `.encode()` and drops the field, so refusing here
  // is also what keeps the two arms agreeing: same input, same answer (none).
  // Reachable from a subject sliced out of a JSON payload or a header.
  if (LONE_SURROGATE.test(candidate.userId)) return null;
  // `.strip()`-equivalent, because the canonicalizer strips: a whitespace-only
  // subject is a phantom actor every such caller merges into.
  if (canonicalize(candidate.userId) === "") return null;

  // ⚠ **This guard is falsy-not-stripped, and that is a KNOWN PAIRED DEFECT
  // carried deliberately rather than fixed here.** Python's
  // `identity_adapter.py` uses the same truthiness test, so a whitespace-only
  // issuer passes BOTH and then canonicalizes to `""` — producing a digest
  // distinct from both a null issuer and an empty one, i.e. one person as two
  // actors. Fixing it on this arm alone would split every issuer-bearing hash
  // across the two SDKs, which is a worse bug than the one being fixed. The
  // corpus pins the shared behaviour (`issuer WHITESPACE-ONLY`), so whichever
  // arm is corrected first reddens the other and forces the paired change.
  const issuerRaw = typeof candidate.issuer === "string" && candidate.issuer ? candidate.issuer : null;
  // A malformed ISSUER costs the issuer, not the identity — the subject still
  // resolves, which is the difference between a degraded actor and no actor.
  //
  // ⚠ **This DIVERGES from Python and the corpus structurally cannot pin it.**
  // There, `hash_user_id` raises `UnicodeEncodeError` on the issuer and
  // `_finish_principal` drops `user_id` entirely; here the subject still
  // hashes, issuer-less — so the same input yields no field on one arm and a
  // digest on the other, one that collides with the same `sub` from a
  // different IdP. Recorded rather than aligned, because dropping a resolvable
  // identity over a malformed issuer is the worse behaviour. The generated
  // corpus cannot carry this case: Python's generator cannot produce a vector
  // for an input that raises.
  const issuer = issuerRaw !== null && !LONE_SURROGATE.test(issuerRaw) ? issuerRaw : null;
  return { userId: candidate.userId, issuer };
}

/** The envelope's `user_id` for one principal, or `null` to omit the field.
 *
 * `raw` mode is UNTAGGED and puts real end-user identity in the collector's
 * database — the vendor's deliberate choice, and why SPEC §11.4 tells a
 * consumer never to treat this field as anonymous.
 *
 * ⚠ **Hashed mode with no key DROPS the field rather than falling back to
 * raw.** The fallback would be a residency breach that looks like success:
 * `user_id` present, populated, and carrying the subject verbatim. Absent is
 * the safe direction — this is additive analytics and never a consent gate.
 */
export function userIdForPrincipal(
  principal: Principal,
  options: {
    mode: UserIdMode;
    tenantId: string;
    key?: Uint8Array | string | null | undefined;
  },
): string | null {
  // `capCodePoints`, not `.slice()`: a plain slice counts UTF-16 units, so an
  // astral subject cut at the boundary ships a LONE SURROGATE — the very thing
  // `normalizePrincipal` refuses on the way IN — and disagrees with Python's
  // `user_id[:128]`, which counts code points.
  if (options.mode === USER_ID_MODE_RAW) {
    return capCodePoints(principal.userId, RAW_USER_ID_MAX_LEN);
  }
  if (options.key === null || options.key === undefined) return null;
  return hashUserId(principal.userId, {
    tenantId: options.tenantId,
    key: options.key,
    issuer: principal.issuer ?? null,
    // Unconditional: this arm has no attested rung, so every principal it
    // hashes is vendor-ASSERTED. A `scheme` option here would be an argument
    // no caller can vary — configurability for a rung the design says is not
    // coming to this SDK.
    scheme: VENDOR_HASH_SCHEME,
  });
}
