/** Principal identity — resolve a raw principal, hash it at the edge.
 *
 * The TypeScript half of Python's `baton/identity.py`. Baton attaches the
 * resolved principal to every event so the Console can group by
 * `(tenant_id, vendor_id, principal.id)`, at whatever grain the vendor
 * resolved (SPEC §11.4).
 *
 * Residency contract: the Console DB is metadata-only and may only ever see
 * the HASH — raw identity must never leave the capture edge. So hashing
 * happens HERE, before an event reaches any console-bound sink.
 *
 * ⚠ **This file and Python's must produce byte-identical digests**, and that
 * is asserted rather than believed: `test/identity.test.ts` runs a corpus
 * GENERATED from Python (`test/identityVectors.json`, regenerated by
 * `scripts/gen_identity_vectors.py`) and compares strings. Same discipline as
 * `scrub.ts` — though NOT its method, which was a hand-mirrored matrix, not a
 * generated corpus — for the same reason: one person reaching two SDKs must be one
 * actor downstream, and nothing but a differential corpus can prove it.
 */

import { createHmac } from "node:crypto";

import { capCodePoints } from "./_text.js";

/** The HMAC KEY GENERATION, and nothing else.
 *
 * It is not a provenance marker and not a privacy classifier. Provenance is
 * `PrincipalWire.source` and the classification is `PrincipalWire.form`, and
 * both ride every mode — including `"raw"`, where no tag exists at all, which
 * is the gap a tag can structurally never close. `h2:` is reserved for a key
 * rotation. SPEC §11.4 and the §13 entry carry the full derivation.
 *
 * ⚠ **This value is a WIRE CONSTANT.** `test/identity.test.ts` pins it against
 * Python's generated corpus by literal, not through this name — an assertion
 * written as ``startsWith(`${HASH_SCHEME}:`)`` is self-referential and cannot
 * see this constant change. */
export const HASH_SCHEME = "h1";

/** Where a principal came from. `"asserted"` is a vendor's own resolver,
 * which nothing in the protocol checks.
 *
 * ⚠ **This SDK emits no other value, and that is a property of the arm rather
 * than of this constant.** SPEC §11.4 also registers `"attested"` — a
 * principal read off a verified token — but TypeScript's `AuthInfo` carries no
 * `claims`, so a subject's location here would be a guess. Asserted is not a
 * degraded attested: on stdio it is the only identity mechanism there is. */
export const PRINCIPAL_SOURCE_ASSERTED = "asserted";

/** What the emitted value IS — the privacy classification, and the only thing
 * SPEC §11.4 lets a consumer classify on. */
export const PRINCIPAL_FORM_HASHED = "hashed";
export const PRINCIPAL_FORM_RAW = "raw";

/** Ceiling on a RAW principal id, mirroring Python's `RAW_PRINCIPAL_ID_MAX_LEN`.
 *
 * Raw mode copies vendor-supplied text onto EVERY event of a call — three
 * tool-call legs plus any annotation — so an unbounded value is unbounded
 * several times over. A hook returning a JWT or a concatenated gateway header
 * is the realistic shape, not a hostile one. */
export const RAW_PRINCIPAL_ID_MAX_LEN = 128;

export const PRINCIPAL_ID_MODE_HASHED = "hashed";
export const PRINCIPAL_ID_MODE_RAW = "raw";
export type PrincipalIdMode = typeof PRINCIPAL_ID_MODE_HASHED | typeof PRINCIPAL_ID_MODE_RAW;

/** `principalIdMode` names a CONFIG choice; `form` names what the emitted
 * value IS. The two vocabularies coincide today and are still two
 * vocabularies — a mode added later need not name its form the same thing,
 * and a consumer classifies on `form` alone. Python keeps the same map
 * (`_FORM_BY_MODE`) for the same reason. */
const FORM_BY_MODE: Record<PrincipalIdMode, string> = {
  [PRINCIPAL_ID_MODE_HASHED]: PRINCIPAL_FORM_HASHED,
  [PRINCIPAL_ID_MODE_RAW]: PRINCIPAL_FORM_RAW,
};

/** Codepoints Python's `str.strip()` removes, measured against CPython rather
 * than assumed — `\s` in JavaScript is the WRONG set in BOTH directions.
 *
 * JS `\s` omits `\x1c`-`\x1f` and `\x85`, which Python strips; and JS `\s`
 * INCLUDES `U+FEFF`, which Python does not. So a BOM-prefixed subject is
 * trimmed by one language and kept by the other, and that subject
 * subject — the shape a value pasted out of a spreadsheet or read from a
 * BOM'd file arrives in — would hash to two different actors across the two
 * SDKs. `.trim()` is therefore never correct here; the corpus carries that
 * exact vector. */
const PYTHON_WHITESPACE = "\\t\\n\\v\\f\\r\\x1c-\\x1f \\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000";
const PYTHON_STRIP = new RegExp(`^[${PYTHON_WHITESPACE}]+|[${PYTHON_WHITESPACE}]+$`, "gu");

/** Matches a string containing an UNPAIRED surrogate.
 *
 * `String.prototype.isWellFormed()` says the same thing more plainly, but it
 * needs `lib: ES2024` and this package declares `ES2022` — a lib bump is a
 * statement about what every consumer must support, which is too broad a
 * change to make for one predicate. Under the `u` flag a valid pair is a
 * single code point and does NOT match, while a lone half does; verified to
 * agree with `isWellFormed()` on both. */
const LONE_SURROGATE = /\p{Surrogate}/u;

/** Pin the principal string once, centrally, so every modality hashes an
 * identical value: NFC-normalize, strip, lowercase — in that order, which is
 * Python's order and is load-bearing (normalizing after stripping can expose
 * new strippable codepoints). */
function canonicalize(rawPrincipal: string): string {
  return pythonStrip(rawPrincipal.normalize("NFC")).toLowerCase();
}

/** Python's `str.strip()`, over exactly the set above. Exported for the
 * server-name rule in `integrations/mcp/annotationName.ts`, which has to agree
 * with Python's on what counts as a blank name. */
export function pythonStrip(value: string): string {
  return value.replace(PYTHON_STRIP, "");
}

/** A raw, UNHASHED principal, as a resolver produced it. */
export interface Principal {
  /** The subject — a stable identifier from the vendor's own
   * system. Never an application id: that names the app and is identical for
   * every one of its users, which merges them into one actor. */
  principalId: string;
  /** The issuing authority, where one exists (the OIDC `iss`). Folded into
   * the hash because a subject is unique only within the provider that minted
   * it, so two identity providers behind one vendor can hand the same subject
   * to different people. */
  issuer?: string | null | undefined;
}

/** HMAC-SHA256 a raw principal into a console-safe, per-tenant `principal.id`.
 *
 * `tenantId` is folded into the HMAC MESSAGE (not just the key) so the same
 * principal under two tenants can never collide or be cross-tenant-correlated.
 * Returns `"<scheme>:<hex>"`.
 *
 * `scheme` is NOT part of the HMAC message, so the digest for a given
 * `(tenantId, principal, issuer)` is identical under every scheme and only the
 * prefix moves. That is what lets the tag mean the KEY GENERATION and nothing
 * else: a rotation to `h2:` is the one event that moves a digest, and a
 * provenance never was.
 *
 * ⚠ **`issuer` null/undefined MUST hash byte-identically to the pre-issuer
 * form** — the append-only message layout is what guarantees it, and every
 * hash baton-proxy and baton-extmcp have produced since 0.5.0 was issuer-less.
 */
export function hashPrincipalId(
  rawPrincipal: string,
  options: {
    tenantId: string;
    key: Uint8Array | string;
    // `| undefined` explicitly, because this repo runs
    // `exactOptionalPropertyTypes`: an optional property there does NOT admit
    // an explicitly-passed `undefined`, and callers forward an absent issuer
    // as one. Both spellings must mean "no issuer" or the two arms of that
    // caller hash differently.
    issuer?: string | null | undefined;
    /** The key generation, defaulting to the current one exactly as Python's
     * does. A caller passes this only to reproduce a digest under a
     * superseded key.
     *
     * `| undefined` explicitly, for the same `exactOptionalPropertyTypes`
     * reason `issuer` carries above — and it bites HARDER here, because this
     * option exists precisely to be omittable. Without it the natural vendor
     * shape, forwarding an optional off their own config
     * (`scheme: cfg.scheme` where `cfg.scheme: string | undefined`), is a
     * compile error on the published types. No in-repo caller can see that:
     * they either omit it or pass a concrete string from the corpus. */
    scheme?: string | undefined;
  },
): string {
  const { tenantId, key, issuer = null, scheme = HASH_SCHEME } = options;
  let message = `${tenantId}\x00${canonicalize(rawPrincipal)}`;
  // `!== null` alone: the destructure above defaults an explicitly-passed
  // `undefined` to `null`, so only one of the two states survives it. The
  // `| undefined` in the option TYPE stays — that is what
  // `exactOptionalPropertyTypes` needs at the call boundary.
  if (issuer !== null) {
    message += `\x00${canonicalize(issuer)}`;
  }
  // A string key is UTF-8 encoded, matching Python's env-var path
  // (`BATON_PRINCIPAL_ID_HMAC_KEY` arrives as text and is `.encode()`d there).
  const keyBytes = typeof key === "string" ? Buffer.from(key, "utf8") : key;
  const digest = createHmac("sha256", keyBytes).update(message, "utf8").digest("hex");
  return `${scheme}:${digest}`;
}

/** Normalize whatever a vendor's hook returned into a usable `Principal`, or
 * `null` if it gave us nothing usable.
 *
 * ⚠ **The shape check is load-bearing, not defensive typing.** TypeScript
 * types vanish at runtime and a hook is vendor code, so a plain string, a
 * dict, or a half-built object is exactly what arrives first — AgentCat's
 * `identify()`, the prior art this is modelled on, returns a bare object. The
 * very next thing that happens to this value is an HMAC over `principalId`, so a
 * wrong return is a MISS, never a partially-built principal.
 *
 * ⚠ **An empty or whitespace-only `principalId` is REJECTED**, and this is a
 * measured divergence from the prior art rather than a stylistic one: their
 * guard is falsy-only, so `{principalId: ""}` reaches their wire. An empty
 * principal canonicalizes to `""` and hashes to one stable digest naming
 * nobody — so every such caller merges into a single phantom actor, which is
 * the exact failure this field exists to prevent.
 */
export function normalizePrincipal(result: unknown): Principal | null {
  if (result === null || typeof result !== "object") return null;
  const candidate = result as { principalId?: unknown; issuer?: unknown };
  if (typeof candidate.principalId !== "string") return null;
  // ⚠ **A lone surrogate MERGES distinct people, so it is a miss.** Node's
  // `update(…, "utf8")` does not throw on an unpaired surrogate — it replaces
  // it with U+FFFD — so `"a\uD800"`, `"a\uDC00"` and `"a\uFFFD"` all hash to
  // ONE digest (measured). That is the actor merge this module exists to
  // prevent, arriving through the quietest possible door. Python raises
  // `UnicodeEncodeError` on `.encode()` and drops the field, so refusing here
  // is also what keeps the two arms agreeing: same input, same answer (none).
  // Reachable from a subject sliced out of a JSON payload or a header.
  if (LONE_SURROGATE.test(candidate.principalId)) return null;
  // `.strip()`-equivalent, because the canonicalizer strips: a whitespace-only
  // subject is a phantom actor every such caller merges into.
  if (canonicalize(candidate.principalId) === "") return null;

  // ⚠ **This guard is falsy-not-stripped, and that is a KNOWN PAIRED DEFECT
  // carried deliberately rather than fixed here.** Python's
  // `identity_adapter.py` uses the same truthiness test, so a whitespace-only
  // issuer passes BOTH and then canonicalizes to `""` — producing a digest
  // distinct from both a null issuer and an empty one, i.e. one person as two
  // actors. Fixing it on this arm alone would split every issuer-bearing hash
  // across the two SDKs, which is a worse bug than the one being fixed. The
  // corpus pins the shared behaviour (`issuer WHITESPACE-ONLY`), so whichever
  // arm is corrected first reddens the other and forces the paired change.
  const issuerRaw = typeof candidate.issuer === "string" && candidate.issuer ? candidate.issuer : null;
  // A malformed ISSUER costs the issuer, not the identity — the subject still
  // resolves, which is the difference between a degraded actor and no actor.
  //
  // ⚠ **This DIVERGES from Python and the corpus structurally cannot pin it.**
  // There, `hash_principal_id` raises `UnicodeEncodeError` on the issuer and
  // `_finish_principal` drops the principal entirely; here the subject still
  // hashes, issuer-less — so the same input yields no field on one arm and a
  // digest on the other, one that collides with the same `sub` from a
  // different IdP. Recorded rather than aligned, because dropping a resolvable
  // identity over a malformed issuer is the worse behaviour. The generated
  // corpus cannot carry this case: Python's generator cannot produce a vector
  // for an input that raises.
  const issuer = issuerRaw !== null && !LONE_SURROGATE.test(issuerRaw) ? issuerRaw : null;
  return { principalId: candidate.principalId, issuer };
}

/** The principal AS EMITTED — the finished envelope value (SPEC §11.4).
 *
 * ⚠ **Not `Principal`, and the two are easy to confuse.** That one is what a
 * vendor's `resolvePrincipal` hook HANDS US: a raw subject and an optional
 * issuer. This one is what we PUT ON THE WIRE after deriving it — the raw
 * value is gone by the time this is built, and nothing here is ever the input
 * to a hash. One is the question, this is the answer.
 *
 * **All three members are REQUIRED, and that is the guarantee the object
 * exists to give.** A producer emits the whole thing or omits `principal`
 * entirely; a partial object is malformed, not a degraded reading. So there is
 * no conformant event carrying an `id` whose `form` a consumer has to guess,
 * and none carrying a `source` for an identity nobody resolved. That binding
 * is structural here precisely because its predecessor — a scheme prefix plus
 * a paragraph of prose — was not.
 */
export interface PrincipalWire {
  /** The value: an HMAC pseudonym in `"hashed"` mode, the principal verbatim
   * in `"raw"` mode. Which one is `form`, and it is NEVER the value's shape —
   * a real OIDC subject (`mailto:`, `acct:`, `urn:`, `https:`) reads as a
   * scheme-tagged pseudonym to anything testing for "letters then a colon". */
  id: string;
  /** WHERE it came from. Always `"asserted"` on this arm — see
   * `PRINCIPAL_SOURCE_ASSERTED`. */
  source: string;
  /** WHAT it is: `"hashed"` or `"raw"`. */
  form: string;
}

/** Turn a resolved principal into the finished wire object, or `null`.
 *
 * **The edge-derivation chokepoint, and the single copy of it**, mirroring
 * Python's `_finish_principal`. `raw` mode puts real identity in the
 * collector's database — the vendor's deliberate choice, and why SPEC §11.4
 * tells a consumer never to treat a principal as anonymous unless `form` says
 * exactly `"hashed"`.
 *
 * ⚠ **Hashed mode with no key DROPS the principal rather than falling back to
 * raw.** The fallback would be a residency breach that looks like success: the
 * field present, populated, and carrying the subject verbatim. Absent is the
 * safe direction — this is additive analytics and never a consent gate.
 *
 * **All three members or nothing**, and structurally so: there is exactly ONE
 * object literal in this function, at the bottom, and every branch that cannot
 * produce a value returns `null` before reaching it.
 *
 * ⚠ Python carries a fourth failure branch here — an unrecognised `mode`,
 * which has no truthful `form`. It is unreachable on this arm:
 * `validateConfig` (`integrations/mcp/config.ts`) refuses an unknown
 * `principalIdMode` at install, so the mode reaching this function is always
 * one of the two. Not porting it is therefore a fact about where the check
 * lives, not a gap.
 */
export function principalFor(
  principal: Principal,
  options: {
    mode: PrincipalIdMode;
    tenantId: string;
    key?: Uint8Array | string | null | undefined;
  },
): PrincipalWire | null {
  let id: string;
  if (options.mode === PRINCIPAL_ID_MODE_RAW) {
    // `capCodePoints`, not `.slice()`: a plain slice counts UTF-16 units, so
    // an astral subject cut at the boundary ships a LONE SURROGATE — the very
    // thing `normalizePrincipal` refuses on the way IN — and disagrees with
    // Python's `principal_id[:128]`, which counts code points.
    //
    // ⚠ What raw mode NO LONGER forfeits is the provenance: `source` is a
    // member now and rides every mode, so a consumer here is told a real
    // identity AND which mechanism named it.
    id = capCodePoints(principal.principalId, RAW_PRINCIPAL_ID_MAX_LEN);
  } else {
    if (options.key === null || options.key === undefined) return null;
    id = hashPrincipalId(principal.principalId, {
      tenantId: options.tenantId,
      key: options.key,
      issuer: principal.issuer ?? null,
    });
  }
  // Unconditional `source`: this arm has no attested rung, so every principal
  // it derives is vendor-ASSERTED. An option here would be an argument no
  // caller can vary — configurability for a rung the design says is not coming
  // to this SDK. When one arrives, the parameter arrives with it.
  return { id, source: PRINCIPAL_SOURCE_ASSERTED, form: FORM_BY_MODE[options.mode] };
}
